car_sales.csv を読み込んで、以下のコメントのとおり、学習データとテストデータに分割するプログラムを実装してください。

In [4]:
# pandas をインポートし、pd という名前で使えるようにする
import pandas as pd

# car_sales.csvを読み込み、df という変数に格納する。
df = pd.read_csv("car_sales.csv")

# df のデータの末尾5件を表示する
df.tail()

    Price_in_thousands  Engine_size  ...  Power_perf_factor  Sales_in_thousands
45              21.620          4.0  ...          76.584440              80.556
46              26.895          4.0  ...          80.387779             157.040
47              31.505          3.0  ...          87.211001              24.072
48              37.805          3.0  ...          94.946698              12.698
49              46.305          4.0  ...         125.013357               3.334

[5 rows x 11 columns]

In [5]:
# 読み込んだcsvデータの行数、列数を表示する
df.shape

(50, 11)

In [6]:
# 読み込んだcsvデータの欠損値の件数を表示する
df.isnull().sum()

Price_in_thousands    0
Engine_size           0
Horsepower            0
Wheelbase             0
Width                 0
Length                0
Curb_weight           0
Fuel_capacity         0
Fuel_efficiency       0
Power_perf_factor     0
Sales_in_thousands    0
dtype: int64

In [11]:
# 説明変数の列（Price_in_thousands から Power_perf_factor までの列 ）のみ取り出して、Xに代入する
X = df.iloc[:, :-1]
# Xの末尾から5行を表示し、適切な列が取得できているか確認する
X.tail()

    Price_in_thousands  Engine_size  ...  Fuel_efficiency  Power_perf_factor
45              21.620          4.0  ...               20          76.584440
46              26.895          4.0  ...               19          80.387779
47              31.505          3.0  ...               23          87.211001
48              37.805          3.0  ...               23          94.946698
49              46.305          4.0  ...               21         125.013357

[5 rows x 10 columns]

In [14]:
# Xの列数、行数を確認する
X.shape

(50, 10)

In [15]:
# 目的変数の列（=Sales_in_thousands 列）のみ取り出して、yに代入する
y = df.iloc[:, -1]
# yの末尾から5行を表示し、適切な列が取得できているか確認する
y.tail()

45     80.556
46    157.040
47     24.072
48     12.698
49      3.334
Name: Sales_in_thousands, dtype: float64

In [16]:
# yの列宇数、行数を確認する
y.shape

(50,)

In [18]:
# データ分割（学習データとテストデータ）のための train_test_split 関数のインポート
from sklearn.model_selection import train_test_split

# 学習データとテストデータに分ける
# 分割は 70%をテストデータにする
# random_stateは、10を設定すること
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.7, random_state = 10)

In [28]:
# X_train の行数を表示する
X_train.shape[0]

15

In [29]:
# X_test の行数を表示する
X_test.shape[0]

35

In [30]:
# y_train の行数を表示する
y_train.shape[0]

15

In [31]:
# y_test の行数を表示する
y_test.shape[0]

35

In [25]:
# X_trainのデータ内容をすべて表示する
X_train

    Price_in_thousands  Engine_size  ...  Fuel_efficiency  Power_perf_factor
11              31.965          3.8  ...               24          85.828408
38              18.575          3.9  ...               16          70.078322
16              46.225          5.7  ...               15         109.509117
48              37.805          3.0  ...               23          94.946698
46              26.895          4.0  ...               19          80.387779
49              46.305          4.0  ...               21         125.013357
8               38.900          2.8  ...               25          83.998724
43              42.800          3.0  ...               21         102.178985
29              16.480          2.0  ...               27          53.566200
25              18.890          3.4  ...               27          71.838039
28              22.245          2.7  ...               26          80.023782
0               21.500          1.8  ...               28          58.280150
15              31.010          3.0  ...               22          83.483094
36              19.460          5.2  ...               17          90.211700
9               21.975          3.1  ...               25          71.181451

[15 rows x 10 columns]

In [33]:
# y_test の内容をすべて表示する
y_test

37     16.767
23     32.299
44     55.557
42     23.713
47     24.072
20     42.593
3      20.397
30     13.462
7       9.231
6      19.747
39    111.313
2       8.588
40     66.692
32     76.034
10     39.350
21     26.402
35      0.916
27     32.775
18    135.126
31     30.696
1      39.384
12     83.257
34     71.186
45     80.556
26      7.854
5       1.380
13     63.729
22     17.947
19     24.629
17    145.519
14      6.536
4      18.780
41     29.450
33      4.734
24     21.855
Name: Sales_in_thousands, dtype: float64

In [27]:
# X_train、y_test が何を示すデータであるか、以下の[]の中に適当な文字を穴埋めし、printで表示してください。
# 全部で4行の内容をprint で表示すること

# 【表示する内容】
# 1行目：X_train は、教師データの中から[  %]分取り出された、[学習 or テスト]データである。
# 2行目：X_train には、[説明変数 or 目的変数] の列だけが格納されている。
# 3行目：y_test は、教師データの中から[  %]分取り出された、[学習 or テスト]データである。
# 4行目：y_test には、[説明変数 or 目的変数] の列だけが格納されている。

print("X_train は、教師データの中から[30%]分取り出された、[学習]データである。")
print("X_train には、[説明変数] の列だけが格納されている。")
print("y_test は、教師データの中から[70%]分取り出された、[テスト]データである。")
print("y_test には、[目的変数] の列だけが格納されている。")

X_train は、教師データの中から[60%]分取り出された、[学習]データである。
X_train には、[説明変数] の列だけが格納されている。
y_test は、教師データの中から[40%]分取り出された、[テスト]データである。
y_test には、[目的変数] の列だけが格納されている。