In [ ]:
# ①Pokemon.csv データを読み込み、先頭から3行を表示する

# pandas のインポート
import pandas as pd

# Pokemon.csvを読み込み、df という変数に格納する。エンコードは utf-8 とする。
df = pd.read_csv("Pokemon.csv")


# dfの先頭から3行を表示する
df.head(3)

   #       Name Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
0  1  Bulbasaur  Grass  Poison  ...       65     45           1      False
1  2    Ivysaur  Grass  Poison  ...       80     60           1      False
2  3   Venusaur  Grass  Poison  ...      100     80           1      False

[3 rows x 13 columns]

**# P170～を参考に、それぞれの統計量を求めましょう**

In [ ]:
# ヒント：Name列だけを取りだして格納するソース↓
dfname = df.loc[:,'Name']
dfname

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [ ]:
# Total　列だけを取り出し、Total列内の最大値はいくつか表示してください
dftotal = df.loc[:,"Total"].max()
dftotal

780

In [ ]:
# Speed 列だけを取り出し、Speed列内の最小値はいくつか表示してください
dfspeed = df.loc[:, "Speed"].min()
dfspeed

5

In [ ]:
# HP列の最頻値、中央値を表示する
dfhp = df.loc[:, "HP"].mode()
print(dfhp)

dfhp = df.loc[:, "HP"].median()
print(dfhp)

0    60
dtype: int64
65.0

In [ ]:
# 'Legendary'列の内容が True の件数を Count メソッドを使って求め表示してください
# 表示形式がSeriesの形式となって問題ありません。
dflege = df[df.loc[:, "Legendary"] == True ].count()
dflege

#             65
Name          65
Type 1        65
Type 2        40
Total         65
HP            65
Attack        65
Defense       65
Sp. Atk       65
Sp. Def       65
Speed         65
Generation    65
Legendary     65
dtype: int64